"""Report renderers (spec §19): CSV, XLSX, PDF, HTML, JSON.

Every renderer consumes the dataset built by app.reports.collector.
HTML embeds evidence screenshots directly (base64) so the report is
self-contained; PDF links/tables summarize evidence. Generated files are
stored via the artifact storage layer.
"""
import csv
import io
import json
from base64 import b64encode
from html import escape

from app import storage


# ---------- helpers ----------

def _screenshot_bytes(key: str | None) -> bytes | None:
    if not key:
        return None
    try:
        return storage.get_bytes(key)
    except Exception:
        return None


def _fmt(v) -> str:
    if v is None:
        return ""
    if isinstance(v, float):
        return f"{v:.2f}"
    return str(v)


def _severity_cell(sev: str) -> str:
    return f'<span class="sev sev-{escape(sev)}">{escape(sev)}</span>'


# ---------- CSV ----------

def render_csv(data: dict) -> tuple[bytes, str]:
    """Flat per-execution CSV (the §19 'test cases + results' export)."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "Ref", "Scenario", "Module", "Category", "Priority", "Kind", "Browser",
        "Status", "Attempt", "Duration_ms", "Worker", "Actual Result", "Error Type",
    ])
    for ex in data["executions"]:
        writer.writerow([
            ex["ref"], ex["scenario"], ex["module"], ex["category"], ex["priority"],
            ex["kind"], ex["browser"], ex["status"], ex["attempt"], ex["duration_ms"] or "",
            ex["worker_id"], ex["actual_result"], ex["error_type"] or "",
        ])
    return buf.getvalue().encode("utf-8"), "text/csv"


# ---------- JSON ----------

def render_json(data: dict) -> tuple[bytes, str]:
    return json.dumps(data, indent=2, default=str).encode("utf-8"), "application/json"


# ---------- HTML ----------

_CSS = """
body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#f6f7f9;color:#1a202c}
.wrap{max-width:960px;margin:0 auto;padding:32px}
h1{font-size:26px}h2{margin-top:36px;border-bottom:2px solid #e2e8f0;padding-bottom:6px}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:20px;margin:14px 0}
table{width:100%;border-collapse:collapse;font-size:13px}
th{background:#edf2f7;text-align:left;padding:8px;border:1px solid #e2e8f0}
td{padding:8px;border:1px solid #e2e8f0;vertical-align:top}
.pass{color:#047857;font-weight:700}.fail{color:#b91c1c;font-weight:700}
.skip{color:#64748b}.sev{padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700}
.sev-critical{background:#fee2e2;color:#991b1b}.sev-high{background:#ffedd5;color:#9a3412}
.sev-medium{background:#fef9c3;color:#854d0e}.sev-low{background:#e2e8f0;color:#334155}
.shot{max-width:100%;border:1px solid #cbd5e0;border-radius:6px;margin:8px 0}
ul{margin:6px 0}li{margin:4px 0}.muted{color:#64748b;font-size:12px}
"""

_STATUS_CLASS = {"passed": "pass", "failed": "fail", "skipped": "skip", "blocked": "skip"}


def render_html(data: dict, embed_screenshots: bool = True) -> tuple[bytes, str]:
    e = escape

    def table(headers: list[str], rows: list[list[str]]) -> str:
        out = ["<table><thead><tr>" + "".join(f"<th>{h}</th>" for h in headers) + "</tr></thead><tbody>"]
        for row in rows:
            out.append("<tr>" + "".join(f"<td>{c}</td>" for c in row) + "</tr>")
        out.append("</tbody></table>")
        return "".join(out)

    parts = [
        f"<!doctype html><html><head><meta charset='utf-8'><title>AutoQA Report — {e(data['application']['name'])}</title>"
        f"<style>{_CSS}</style></head><body><div class='wrap'>",
        f"<h1>AutoQA QA Report — {e(data['application']['name'])}</h1>",
        f"<p class='muted'>Target {e(data['application']['base_url'])} · generated {e(data['generated_at'])} · "
        f"platform {e(data['environment']['platform'])}</p>",

        "<h2>Executive Summary</h2><div class='card'><ul>",
        *[f"<li>{e(line)}</li>" for line in data["executive_summary"]],
        "</ul></div>",

        "<h2>Application Information</h2><div class='card'>",
        table(["Attribute", "Value"], [
            ["Frontend stack", e(json.dumps(data["application"]["frontend_stack"]) or "{}")],
            ["Backend stack", e(json.dumps(data["application"]["backend_stack"]) or "{}")],
            ["Pages discovered", str(data["application"]["pages_discovered"])],
            ["APIs discovered", str(data["application"]["apis_discovered"])],
            ["Authorization confirmed", "Yes" if data["application"]["authorization_confirmed"] else "No"],
            ["Browsers", e(", ".join(data["environment"]["browsers"]))],
        ]),
        "</div>",
    ]

    if data["test_plan"]:
        plan = data["test_plan"]
        parts += [
            f"<h2>Test Plan (v{plan['version']}, generated by {e(plan['generated_by'])})</h2><div class='card'>",
            f"<p><b>Objective:</b> {e(plan['objective'])}</p>",
            table(["Section", "Content", "Priority"], [
                [e(s.get("section", "")), e(s.get("content", "")), e(s.get("priority", ""))]
                for s in plan["sections"][:30]
            ]),
            "</div>",
        ]

    parts += [
        "<h2>Execution Summary</h2><div class='card'>",
        table(["Metric", "Value"], [
            ["Total executions", str(data["counters"]["total"])],
            ["Passed", f"<span class='pass'>{data['counters']['passed']}</span>"],
            ["Failed", f"<span class='fail'>{data['counters']['failed']}</span>"],
            ["Skipped", str(data["counters"]["skipped"])],
            ["Blocked", str(data["counters"]["blocked"])],
            ["Pass rate", f"{data['counters']['pass_rate']}%"],
        ]),
        "</div>",

        "<h2>Test Cases &amp; Results</h2><div class='card'>",
        table(["Ref", "Module", "Browser", "Status", "Duration (ms)", "Actual result"], [
            [
                e(ex["ref"]), e(ex["module"]), e(ex["browser"]),
                f"<span class='{_STATUS_CLASS.get(ex['status'], 'skip')}'>{e(ex['status'])}</span>",
                _fmt(ex["duration_ms"]), e((ex["actual_result"] or "")[:120]),
            ]
            for ex in data["executions"][:200]
        ]),
        "</div>",
    ]

    failed_with_shots = [ex for ex in data["executions"] if ex["status"] == "failed"]
    if failed_with_shots:
        parts.append("<h2>Failed Tests &amp; Evidence</h2>")
        for ex in failed_with_shots[:20]:
            parts.append(
                f"<div class='card'><b>{e(ex['ref'])}</b> — {e(ex['scenario'][:100])}<br>"
                f"<span class='muted'>browser {e(ex['browser'])} · attempt {ex['attempt']} · "
                f"error {e(ex['error_type'] or '?')}</span>"
                f"<p>{e(ex['actual_result'] or '')[:300]}</p>"
            )
            if ex["console"]:
                parts.append(f"<p class='muted'>console: {e(' | '.join(ex['console'][-3:]))}</p>")
            if embed_screenshots and ex["screenshot_key"]:
                shot = _screenshot_bytes(ex["screenshot_key"])
                if shot:
                    b64 = b64encode(shot).decode()
                    parts.append(f"<img class='shot' src='data:image/png;base64,{b64}' alt='screenshot {e(ex['ref'])}'>")
            parts.append("</div>")

    if data["defects"]:
        parts += [
            "<h2>Defects</h2><div class='card'>",
            table(["Severity", "Title", "Module", "Possible root cause", "Recommended investigation"], [
                [_severity_cell(d["severity"]), e(d["title"][:80]), e(d["module"]),
                 e(d["possible_root_cause"][:140]), e(d["recommended_investigation"][:140])]
                for d in data["defects"][:50]
            ]),
            "</div>",
        ]

    if data["security_findings"]:
        parts += [
            "<h2>Security Findings</h2><div class='card'>",
            table(["Severity", "Title", "Evidence", "Remediation"], [
                [_severity_cell(f["severity"]), e(f["title"][:80]), e(f["evidence_url"]),
                 e(f["remediation"][:120])]
                for f in data["security_findings"][:50]
            ]),
            "</div>",
        ]

    if data["performance"]:
        parts += [
            "<h2>Performance Results</h2><div class='card'>",
            table(["Scenario", "Users", "p50 (ms)", "p95 (ms)", "p99 (ms)", "RPS", "Errors", "Threshold"], [
                [e(p["scenario"]), str(p["concurrent_users"]), _fmt(p["p50_ms"]), _fmt(p["p95_ms"]),
                 _fmt(p["p99_ms"]), _fmt(p["throughput_rps"]), f"{p['error_rate'] * 100:.1f}%",
                 "BREACHED" if p["threshold_breached"] else "ok"]
                for p in data["performance"][:20]
            ]),
            "</div>",
        ]

    if data["accessibility"]:
        parts += [
            "<h2>Accessibility Results</h2><div class='card'>",
            table(["Page", "Violations", "By severity", "Rules"], [
                [e(a["page_url"][:60]), str(a["violation_count"]),
                 e(", ".join(f"{k}:{v}" for k, v in a["by_severity"].items())),
                 e(", ".join(a["rules"][:8]))]
                for a in data["accessibility"][:30]
            ]),
            "</div>",
        ]

    parts += [
        "<h2>Recommendations</h2><div class='card'><ul>",
        *[f"<li>{e(r)}</li>" for r in data["recommendations"]],
        "</ul></div>",
        f"<p class='muted'>Generated by AutoQA — evidence-grounded QA reporting.</p>",
        "</div></body></html>",
    ]
    return "".join(parts).encode("utf-8"), "text/html"


# ---------- XLSX ----------

def render_xlsx(data: dict) -> tuple[bytes, str]:
    from openpyxl import Workbook
    from openpyxl.styles import Font

    wb = Workbook()

    ws = wb.active
    ws.title = "Summary"
    ws.append(["AutoQA QA Report", data["application"]["name"]])
    ws.append(["Target", data["application"]["base_url"]])
    ws.append(["Generated", data["generated_at"]])
    ws.append([])
    ws.append(["Metric", "Value"])
    for k, label in [("total", "Total executions"), ("passed", "Passed"), ("failed", "Failed"),
                     ("skipped", "Skipped"), ("blocked", "Blocked"), ("pass_rate", "Pass rate %")]:
        ws.append([label, data["counters"][k]])
    ws.append([])
    ws.append(["Executive summary"])
    for line in data["executive_summary"]:
        ws.append(["•", line])
    ws["A1"].font = Font(bold=True, size=14)

    ws = wb.create_sheet("Executions")
    headers = ["Ref", "Scenario", "Module", "Category", "Priority", "Kind", "Browser",
               "Status", "Attempt", "Duration_ms", "Worker", "Actual Result"]
    ws.append(headers)
    for c in ws[1]:
        c.font = Font(bold=True)
    for ex in data["executions"]:
        ws.append([
            ex["ref"], ex["scenario"], ex["module"], ex["category"], ex["priority"],
            ex["kind"], ex["browser"], ex["status"], ex["attempt"], ex["duration_ms"],
            ex["worker_id"], ex["actual_result"],
        ])

    if data["defects"]:
        ws = wb.create_sheet("Defects")
        ws.append(["Severity", "Title", "Module", "Description", "Possible root cause", "Recommended investigation", "Status"])
        for c in ws[1]:
            c.font = Font(bold=True)
        for d in data["defects"]:
            ws.append([d["severity"], d["title"], d["module"], d["description"],
                       d["possible_root_cause"], d["recommended_investigation"], d["status"]])

    if data["security_findings"]:
        ws = wb.create_sheet("Security")
        ws.append(["Severity", "Title", "Evidence URL", "Remediation", "Status"])
        for c in ws[1]:
            c.font = Font(bold=True)
        for f in data["security_findings"]:
            ws.append([f["severity"], f["title"], f["evidence_url"], f["remediation"], f["status"]])

    if data["performance"]:
        ws = wb.create_sheet("Performance")
        ws.append(["Scenario", "Users", "p50_ms", "p90_ms", "p95_ms", "p99_ms", "RPS", "Error rate", "Threshold breached", "Date"])
        for c in ws[1]:
            c.font = Font(bold=True)
        for p in data["performance"]:
            ws.append([p["scenario"], p["concurrent_users"], p["p50_ms"], p["p90_ms"],
                       p["p95_ms"], p["p99_ms"], p["throughput_rps"], p["error_rate"],
                       bool(p["threshold_breached"]), p["created_at"]])

    if data["accessibility"]:
        ws = wb.create_sheet("Accessibility")
        ws.append(["Page", "Violations", "By severity", "Rules"])
        for c in ws[1]:
            c.font = Font(bold=True)
        for a in data["accessibility"]:
            ws.append([a["page_url"], a["violation_count"],
                       ", ".join(f"{k}:{v}" for k, v in a["by_severity"].items()),
                       ", ".join(a["rules"])])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"


# ---------- PDF ----------

def render_pdf(data: dict) -> tuple[bytes, str]:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        Image,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    styles = getSampleStyleSheet()
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], spaceBefore=14, spaceAfter=6)
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=9, leading=12)
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=7.5, leading=9.5,
                           textColor=colors.HexColor("#4a5568"))

    def _table(headers: list[str], rows: list[list[str]], widths: list[float] | None = None) -> Table:
        body = [
            [Paragraph(f"<b>{h}</b>", small) for h in headers]
        ] + [
            [Paragraph(str(c)[:180], small) for c in row] for row in rows
        ]
        t = Table(body, colWidths=widths, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#edf2f7")),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e0")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTSIZE", (0, 0), (-1, -1), 7.5),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        return t

    story: list = [
        Paragraph(f"AutoQA QA Report — {data['application']['name']}", styles["Title"]),
        Paragraph(
            f"Target {data['application']['base_url']} · generated {data['generated_at']} · "
            f"platform {data['environment']['platform']}",
            small,
        ),
        Paragraph("Executive Summary", h2),
    ]
    for line in data["executive_summary"]:
        story.append(Paragraph(f"• {line}", body))

    story.append(Paragraph("Execution Summary", h2))
    story.append(_table(
        ["Metric", "Value"],
        [["Total", str(data["counters"]["total"])],
         ["Passed", str(data["counters"]["passed"])],
         ["Failed", str(data["counters"]["failed"])],
         ["Skipped", str(data["counters"]["skipped"])],
         ["Pass rate %", str(data["counters"]["pass_rate"])]],
        widths=[6 * cm, 4 * cm],
    ))

    story.append(Paragraph("Test Cases & Results", h2))
    story.append(_table(
        ["Ref", "Module", "Browser", "Status", "ms", "Actual result"],
        [[ex["ref"], ex["module"], ex["browser"], ex["status"],
          _fmt(ex["duration_ms"]), (ex["actual_result"] or "")[:90]]
         for ex in data["executions"][:80]],
        widths=[3.2 * cm, 2.6 * cm, 1.9 * cm, 1.9 * cm, 1.4 * cm, 6 * cm],
    ))

    if data["defects"]:
        story.append(PageBreak())
        story.append(Paragraph("Defects", h2))
        story.append(_table(
            ["Severity", "Title", "Module", "Possible root cause"],
            [[d["severity"], d["title"][:70], d["module"], d["possible_root_cause"][:120]]
             for d in data["defects"][:30]],
            widths=[2 * cm, 5.5 * cm, 2.5 * cm, 7 * cm],
        ))

    if data["security_findings"]:
        story.append(Paragraph("Security Findings", h2))
        story.append(_table(
            ["Severity", "Title", "Remediation"],
            [[f["severity"], f["title"][:70], f["remediation"][:110]]
             for f in data["security_findings"][:30]],
            widths=[2 * cm, 7.5 * cm, 7.5 * cm],
        ))

    if data["performance"]:
        story.append(Paragraph("Performance Results", h2))
        story.append(_table(
            ["Scenario", "Users", "p50", "p95", "p99", "RPS", "Errors", "Threshold"],
            [[p["scenario"], str(p["concurrent_users"]), _fmt(p["p50_ms"]), _fmt(p["p95_ms"]),
              _fmt(p["p99_ms"]), _fmt(p["throughput_rps"]), f"{p['error_rate'] * 100:.0f}%",
              "BREACH" if p["threshold_breached"] else "ok"]
             for p in data["performance"][:15]],
            widths=[3.4 * cm, 1.4 * cm, 1.6 * cm, 1.6 * cm, 1.6 * cm, 1.6 * cm, 1.5 * cm, 2 * cm],
        ))

    if data["accessibility"]:
        story.append(Paragraph("Accessibility Results", h2))
        story.append(_table(
            ["Page", "Violations", "By severity", "Rules"],
            [[a["page_url"][:45], str(a["violation_count"]),
              ", ".join(f"{k}:{v}" for k, v in a["by_severity"].items()),
              ", ".join(a["rules"][:6])]
             for a in data["accessibility"][:20]],
            widths=[4.8 * cm, 1.9 * cm, 4.4 * cm, 5.9 * cm],
        ))

    # Failure evidence with embedded screenshots.
    # Validate bytes with PIL up front: reportlab parses images lazily at
    # build() time, so broken files would otherwise fail the whole report.
    failed_shots = [ex for ex in data["executions"] if ex["status"] == "failed" and ex["screenshot_key"]][:6]
    embeddable = []
    for ex in failed_shots:
        shot = _screenshot_bytes(ex["screenshot_key"])
        if not shot:
            continue
        try:
            from PIL import Image as PILImage

            PILImage.open(io.BytesIO(shot)).verify()
        except Exception:
            continue
        embeddable.append((ex, shot))
    if embeddable:
        story.append(PageBreak())
        story.append(Paragraph("Failed Tests — Evidence Screenshots", h2))
        for ex, shot in embeddable:
            story.append(Paragraph(f"<b>{ex['ref']}</b> — {ex['scenario'][:80]} ({ex['browser']}, attempt {ex['attempt']})", body))
            story.append(Paragraph(str(ex["actual_result"] or "")[:220], small))
            try:
                img = Image(io.BytesIO(shot), width=14 * cm, height=7.875 * cm)
                img._restrictSize(14 * cm, 9 * cm)
                story.append(img)
            except Exception:
                story.append(Paragraph("[screenshot could not be embedded]", small))
            story.append(Spacer(1, 10))

    story.append(Paragraph("Recommendations", h2))
    for r in data["recommendations"]:
        story.append(Paragraph(f"• {r}", body))

    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=A4, leftMargin=1.5 * cm, rightMargin=1.5 * cm,
                      topMargin=1.5 * cm, bottomMargin=1.5 * cm).build(story)
    return buf.getvalue(), "application/pdf"


RENDERERS = {
    "csv": render_csv,
    "json": render_json,
    "html": render_html,
    "xlsx": render_xlsx,
    "pdf": render_pdf,
}
